# networks:
    #   - directus
    environment:
      KEY: '255d861b-5ea1-1996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-1667-b5b5-c8022c45e263'

      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres-development-132'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://redis:6379'

      ADMIN_EMAIL: 'nhatnn@metainc.cc'
      ADMIN_PASSWORD: 'emyeuanh1'

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: 'https://directus.example.com'

  m3ta-frontend:
    image: m3ta-frontend
    build: m3ta-fe
    ports:
      - 80:3000
    environment:
      CMS_DOMAIN: http://directus:8055
      URL_IMAGE: directus
      MODE: DEVELOPMENT